version: '3.8'

services:
  db:
    image: postgres:16
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./oldb-backend/src/main/resources/db/init-schemas.sql:/docker-entrypoint-initdb.d/01-init-schemas.sql:ro

volumes:
  postgres_data:
